# Generated by Django 4.0.10 on 2023-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contract_id', models.IntegerField()),
                ('acceptor_id', models.IntegerField()),
                ('assignee_id', models.IntegerField()),
                ('issuer_id', models.IntegerField()),
                ('issuer_corporation_id', models.IntegerField()),
                ('collateral', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('buyout', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('days_to_complete', models.IntegerField(blank=True, null=True)),
                ('start_location_id', models.BigIntegerField(blank=True, null=True)),
                ('end_location_id', models.BigIntegerField(blank=True, null=True)),
                ('for_corporation', models.BooleanField()),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('date_expired', models.DateTimeField()),
                ('date_issued', models.DateTimeField()),
                ('status', models.CharField(max_length=25)),
                ('contract_type', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
