# Generated by Django 4.0.10 on 2024-03-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fittings', '0016_remove_dogmaattribute_type_remove_dogmaeffect_type_and_more'),
        ('aadoctrinecontracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='matched_fitting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='fittings.fitting', blank=True, null=True),
        ),
    ]
